### ISSUE TITLE
Question about the dataset

### ISSUE THREAD

**Issue by aruiplex** [Lizn-zn/Nesy-Programming#1]
Hi, could you explain the SudoKu dataset you used in the code? What are the `board.pt`, `board_img.pt`, `label.pt`, and `input_mask.pt`? How can I get them? I already found the RRN and SATNet repos. Could you give me some advice to let me reproduce your paper?

Thanks.

**Comment by Lizn-zn** [comment]
You can download the dataset from this [Google-Drive](https://drive.google.com/drive/folders/12Fs5UKSa1zSOIAv42Xd4mqLdnF_mo8Uv?usp=sharing). The dataset is consistent with that of SATNet and RRN paper. To reproduce our result, you can run the `./run.sh` in each task folder.
